markdown:    redcarpet
highlighter: pygments

permalink: /posts/:year/:month/:title
relative_permalinks: true

title: Aravin Suganthan
url: https://aravin-s.github.io/
# baseurl: /
description: Aravin Suganthan Portfolio

paginate: 5
paginate_path: '/:num'

exclude: [Gemfile, Gemfile.lock, gulpfile.js, package.json, node_modules, css, scripts]
